image: node:lts

cache:
  paths:
    - node_modules/

before_script:
  - npm ci --no-audit

pages:
  script:
    - npm run storybook:build
    - mv storybook-dist public
  artifacts:
    paths:
    - public
